collectif_index:
    path:     /
    defaults: { _controller: "ModuleGestionBundle:Collectif:index" }
    methods:  GET

collectif_show:
    path:     /{id}/show
    defaults: { _controller: "ModuleGestionBundle:Collectif:show" }
    methods:  GET

collectif_new:
    path:     /new
    defaults: { _controller: "ModuleGestionBundle:Collectif:new" }
    methods:  [GET, POST]

collectif_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModuleGestionBundle:Collectif:edit" }
    methods:  [GET, POST]

collectif_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModuleGestionBundle:Collectif:delete" }
    methods:  DELETE
