organisateur_index:
    path:     /
    defaults: { _controller: "ModuleGestionBundle:Organisateur:index" }
    methods:  GET

organisateur_show:
    path:     /{id}/show
    defaults: { _controller: "ModuleGestionBundle:Organisateur:show" }
    methods:  GET

organisateur_new:
    path:     /new
    defaults: { _controller: "ModuleGestionBundle:Organisateur:new" }
    methods:  [GET, POST]

organisateur_edit:
    path:     /{id}/edit
    defaults: { _controller: "ModuleGestionBundle:Organisateur:edit" }
    methods:  [GET, POST]

organisateur_delete:
    path:     /{id}/delete
    defaults: { _controller: "ModuleGestionBundle:Organisateur:delete" }
    methods:  DELETE
