app:
    resource: '@AppBundle/Controller/'
    type: annotation

module_diffusion:
    resource: "@ModuleDiffusionBundle/Resources/config/routing.yml"
    prefix:   /

module_gestion:
    resource: "@ModuleGestionBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
