# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: ModuleGestionBundle\Form\UtilisateurType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.scan_oeuvre:
        class: ModuleGestionBundle\Controller\ScanController

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    modulediffusionbundle.calendar_listener:
      class: ModuleDiffusionBundle\EventListener\CalendarEventListener
      tags:
        -    { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
      arguments:
        - "@doctrine.orm.entity_manager"

