services:
#    module_gestion.example:
#        class: ModuleGestionBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    modulegestion.password_resetting:
        class: ModuleGestionBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }