<?php

namespace ModuleGestionBundle\Repository;

/**
 * CollectifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectifRepository extends \Doctrine\ORM\EntityRepository
{
}
