<?php

namespace ModuleGestionBundle\Repository;

/**
 * EmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementRepository extends \Doctrine\ORM\EntityRepository
{
	public function updateVisite($idO, $idE,$em)
	{
		$qb = $em->createQueryBuilder();
		$q = $qb->update('ModuleGestionBundle\Entity\Emplacement', 'e')
		    ->set('e.nombreVisiteOeuvre', 'e.nombreVisiteOeuvre + 1')
		    ->where('e.oeuvre = ?1')
		    ->andWhere('e.exposition = ?2')
		    ->setParameters(array(
		    	1 => $idO,
		    	2 => $idE,
		    ))
		    ->getQuery();
		$p = $q->execute();
	}
}
