<?php

namespace ModuleGestionBundle\Repository;

/**
 * ExpositionOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
