<?php

namespace ModuleGestionBundle\Repository;

/**
 * MultimediaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
