<?php

namespace ModuleGestionBundle\Repository;

/**
 * TextExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextExpositionRepository extends \Doctrine\ORM\EntityRepository
{
}
