<?php

namespace ModuleGestionBundle\Repository;

/**
 * TexteOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
