<?php

namespace ModuleGestionBundle\Repository;

/**
 * TypeOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
