<?php

namespace ModuleGestionBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{

	public function findMailUser(){

		$query = $this->_em->createQuery('
			SELECT u.firstname,u.lastname,u.email
			FROM ModuleGestionBundle:Utilisateur u');

		return $query->getResult();
	}
}
